In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [10]:
b=[1,2,3]
b*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [4]:
y=[1,2,3,"hello"]
y

[1, 2, 3, 'hello']

In [11]:
x=np.array([1,2,"hello",9.5])
x


array(['1', '2', 'hello', '9.5'], dtype='<U32')

In [ ]:
#numpy--->int,float(calculations we will use)

In [14]:
#creation of numpy array
x=np.array([3,1,3,41,6,7,8])
x

array([ 3,  1,  3, 41,  6,  7,  8])

In [ ]:
#using arange function
#start,step,stop
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [17]:
#find me all the even numbers b/w 1 to 30 and do the square of these numbers
x1=np.arange(2,31,2)
x1**2

array([  4,  16,  36,  64, 100, 144, 196, 256, 324, 400, 484, 576, 676,
       784, 900])

In [19]:
#using linespace
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.ones(3)

array([1., 1., 1.])

In [26]:
np.random.randint(1,100,15)

array([60, 20, 71, 65, 14, 47, 39, 41,  6, 51, 53, 25, 29, 67, 19],
      dtype=int32)

In [30]:
#to fix setof random numbers
np.random.seed(2)
np.random.randint(1,50,15)

array([41, 16, 46,  9, 23, 44, 19, 12, 41,  8, 35, 32, 12, 22, 48],
      dtype=int32)

In [ ]:
#create two set of numpy array of A and B array of same length
#create the numpy array using random functions and do these operation
#a**2+b**2+2(a*b)

In [34]:
np.random.seed(3)
a=np.random.randint(1,10,6)
a
np.random.seed(4)
b=np.random.randint(1,10,6)
b

array([8, 6, 2, 9, 8, 9], dtype=int32)

In [42]:
a**2+b**2+2*a*b


array([289, 100, 121, 324,  81, 225], dtype=int32)

In [47]:
#multidimensional array
a=np.random.randint(1,100,(3,4))
b=np.random.randint(1,100,(4,3))

In [58]:
#findout (a+b)**3
a

array([[ 4,  1, 56, 22],
       [22, 74, 39, 57],
       [67, 47, 31,  9]], dtype=int32)

In [59]:
b

array([[50, 67, 59],
       [88, 33, 41],
       [43, 46, 34],
       [33, 29,  4]], dtype=int32)

In [57]:
#1d  #2d #3d #4d
#x  # x*y  x*y*z
x=np.random.randint(1,100,18)
#  18= 2d--->(2,9),(3,6),(6,3),(9,2)
#18= 3d--->(1,2,9),(2,3,3)
#18=4d-->(1,2,3,3)
x.reshape(6,3)
x.reshape(18)
x.reshape(1,2,9)
x.reshape(1,1,2,3,3)

array([[[[[50,  5,  4],
          [13, 97, 27],
          [71, 82, 58]],

         [[36, 82, 51],
          [16, 80, 36],
          [35, 29, 77]]]]], dtype=int32)

In [ ]:
#create a 3d array  which will have only even numbers between 1 to 60
# i need 10 random even numbers between 1 to 60
#then convert it into 1d array

In [61]:
x=np.arange(2,61,2).reshape(2,3,5)
x

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20],
        [22, 24, 26, 28, 30]],

       [[32, 34, 36, 38, 40],
        [42, 44, 46, 48, 50],
        [52, 54, 56, 58, 60]]])

In [65]:
y=x.reshape(30)
y

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [66]:
np.random.choice(y,10)

array([54, 44,  6, 48, 32, 20, 44, 46, 30, 12])

In [68]:
#find out the numebrs which is completely divisble by 3 and 7 between 100 
#get the final result into 2d array
x=np.arange(1,101,1)
x


array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [78]:
x[(x%3==0)&(x%7==0)].reshape(2,2)

array([[21, 42],
       [63, 84]])

In [ ]:
np.random.seed(42)
x=np.random.randint(1,100,(5,6))
x
#2,88
#68,21

array([[52, 93, 15, 72, 61, 21],
       [83, 87, 75, 75, 88, 24],
       [ 3, 22, 53,  2, 88, 30],
       [38,  2, 64, 60, 21, 33],
       [76, 58, 22, 89, 49, 91]], dtype=int32)

In [88]:
x[2:4:1,3:5:1]

array([[ 2, 88],
       [60, 21]], dtype=int32)

In [95]:
#21 33
#49 91
#75 75
#64 60
x[3:5:1,4:6:1]

array([[21, 33],
       [49, 91]], dtype=int32)

In [96]:
x[1:3:1,4:6:1]

array([[88, 24],
       [88, 30]], dtype=int32)